name: srcnn
channels:
  - https://mirrors.sustech.edu.cn/anaconda/pkgs/main
  - https://mirrors.sustech.edu.cn/anaconda/pkgs/free
  - https://mirrors.sustech.edu.cn/anaconda/pkgs/r
  - https://mirrors.sustech.edu.cn/anaconda/pkgs/pro
  - https://mirrors.sustech.edu.cn/anaconda/pkgs/msys2

dependencies:
  - pip=20.0
  - python=3.6.2
  - numpy
  - scipy=0.19.1
  - matplotlib=3.3.4
  - h5py=2.8.0
  - pip:
    - tensorflow==1.15.0
  